[[benchmark]]
buildCommand = "{buildExtra}; midppl crbd-unaligned.mc --resample likelihood -m rootppl-smc; rootppl out.cu -j 32 --ess_threshold 1.0 --stack_size 1000"
[benchmark.app]
cwd = "/home/dlunde/box/forskning/miking-benchmarks/benchmark-suite/benchmarks/ppl/align/."
fileName = "experiment.toml"
runtime = "CorePPL"
[[benchmark.app.options]]
contents = "10000"
name = "options"
[[benchmark.app.options]]
contents = "crbd-unaligned.mc --resample likelihood"
name = "argument"
[[benchmark.app.options]]
contents = "-j 32 --ess_threshold 1.0 --stack_size 1000"
name = "buildOptions"
[[benchmark.results]]
command = "./program 10000"
ms_build = 2157.75610352
ms_run = [806.148925781, 718.488769531, 593.004882812, 881.277587891, 691.411865234, 687.103027344, 439.781738281, 704.239746094, 703.672851562, 869.790039062, 572.207763672, 554.235839844, 533.184814453, 525.074951172, 746.779785156]
[benchmark.results.input]
cwd = ""
data = ""
tags = []
[[benchmark.results.post]]
output = ["""
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
""", """
"""]
[benchmark.results.post.app]
cwd = "/home/dlunde/box/forskning/miking-benchmarks/benchmark-suite/benchmarks/ppl/align/."
fileName = "experiment.toml"
runtime = "id"
[[benchmark]]
buildCommand = "{buildExtra}; midppl crbd-unaligned.mc --resample align -m rootppl-smc; rootppl out.cu -j 32 --ess_threshold 1.0 --stack_size 1000"
[benchmark.app]
cwd = "/home/dlunde/box/forskning/miking-benchmarks/benchmark-suite/benchmarks/ppl/align/."
fileName = "experiment.toml"
runtime = "CorePPL"
[[benchmark.app.options]]
contents = "10000"
name = "options"
[[benchmark.app.options]]
contents = "crbd-unaligned.mc --resample align"
name = "argument"
[[benchmark.app.options]]
contents = "-j 32 --ess_threshold 1.0 --stack_size 1000"
name = "buildOptions"
[[benchmark.results]]
command = "./program 10000"
ms_build = 2086.89501953
ms_run = [474.95703125, 473.302001953, 470.973876953, 480.168701172, 475.531982422, 475.289794922, 474.979003906, 476.330078125, 477.684082031, 478.157958984, 475.115722656, 477.603027344, 473.298828125, 474.782958984, 475.738769531]
[benchmark.results.input]
cwd = ""
data = ""
tags = []
[[benchmark.results.post]]
output = ["""-304.992562

""", """-304.812287

""", """-304.812287

""", """-305.087002

""", """-305.087002

""", """-305.064840

""", """-305.064840

""", """-305.064840

""", """-304.924576

""", """-304.924576

""", """-304.782750

""", """-304.782750

""", """-304.420065

""", """-304.420065

""", """-304.503431

"""]
[benchmark.results.post.app]
cwd = "/home/dlunde/box/forskning/miking-benchmarks/benchmark-suite/benchmarks/ppl/align/."
fileName = "experiment.toml"
runtime = "id"
