boot eval tool/main/main.mc -- \
  --benchmarks benchmark-suite/benchmarks/ppl/rootppl \
  --runtimes benchmark-suite/runtimes \
  --iters 10 \
  --output toml \
  --warmups 1
make[1]: Entering directory '/home/viktor/.local/lib/rootppl'
rm -f out/*.o
make[1]: Leaving directory '/home/viktor/.local/lib/rootppl'
make[1]: Entering directory '/home/viktor/.local/lib/rootppl'
rm -f out/*.o
make[1]: Leaving directory '/home/viktor/.local/lib/rootppl'
make[1]: Entering directory '/home/viktor/.local/lib/rootppl'
rm -f out/*.o
make[1]: Leaving directory '/home/viktor/.local/lib/rootppl'
make[1]: Entering directory '/home/viktor/.local/lib/rootppl'
rm -f out/*.o
make[1]: Leaving directory '/home/viktor/.local/lib/rootppl'
make[1]: Entering directory '/home/viktor/.local/lib/rootppl'
rm -f out/*.o
make[1]: Leaving directory '/home/viktor/.local/lib/rootppl'
make[1]: Entering directory '/home/viktor/.local/lib/rootppl'
rm -f out/*.o
make[1]: Leaving directory '/home/viktor/.local/lib/rootppl'
[[benchmark]]

[[benchmark.results]]
ms_run = [ 251.7939453125, 193.9990234375, 237.13818359375, 205.9169921875, 184.960205078125, 220.152099609375, 176.4169921875, 227.357177734375, 215.40673828125, 169.48486328125,]
ms_build = 486.597900390625
[[benchmark.results.post]]
stdout = [ "log normalization constant = -253.463499\n\n", "log normalization constant = -255.475423\n\n", "log normalization constant = -255.082665\n\n", "log normalization constant = -247.137507\n\n", "log normalization constant = -260.664577\n\n", "log normalization constant = -256.424660\n\n", "log normalization constant = -244.462209\n\n", "log normalization constant = -248.612142\n\n", "log normalization constant = -245.532356\n\n", "log normalization constant = -240.536509\n\n",]

[benchmark.results.post.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = ""
runtime = "id"
argument = ""
buildOptions = ""

[benchmark.results.input]
cwd = ""
data = ""
file = ""
tags = ""
[benchmark.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = "20000 1"
runtime = "RootPPL"
argument = "Alcedinidae_crbd.cu"
buildOptions = "--omp -j 32"
[[benchmark]]

[[benchmark.results]]
ms_run = [ 251.06201171875, 228.561767578125, 246.80810546875, 223.73095703125, 227.127197265625, 218.923828125, 218.96875, 221.535400390625, 220.592041015625, 232.238037109375,]
ms_build = 5035.051025390625
[[benchmark.results.post]]
stdout = [ "log normalization constant = -260.291801\n\n", "log normalization constant = -254.635033\n\n", "log normalization constant = -256.264552\n\n", "log normalization constant = -253.324408\n\n", "log normalization constant = -257.485571\n\n", "log normalization constant = -251.590892\n\n", "log normalization constant = -248.109693\n\n", "log normalization constant = -253.532705\n\n", "log normalization constant = -256.338770\n\n", "log normalization constant = -260.092606\n\n",]

[benchmark.results.post.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = ""
runtime = "id"
argument = ""
buildOptions = ""

[benchmark.results.input]
cwd = ""
data = ""
file = ""
tags = ""
[benchmark.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = "20000 1"
runtime = "RootPPL"
argument = "Alcedinidae_crbd.cu"
buildOptions = "--arch 75 -j 32"
[[benchmark]]

[[benchmark.results]]
ms_run = [ 357.6279296875, 372.056884765625, 395.3369140625, 395.89404296875, 398.02783203125, 375.0009765625, 365.2138671875, 370.864990234375, 382.273193359375, 373.373046875,]
ms_build = 2517.154052734375
[[benchmark.results.post]]
stdout = [ "log normalization constant = -245.273045\n\n", "log normalization constant = -245.273045\n\n", "log normalization constant = -250.750068\n\n", "log normalization constant = -250.750068\n\n", "log normalization constant = -250.750068\n\n", "log normalization constant = -259.894745\n\n", "log normalization constant = -259.894745\n\n", "log normalization constant = -259.894745\n\n", "log normalization constant = -248.543783\n\n", "log normalization constant = -248.543783\n\n",]

[benchmark.results.post.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = ""
runtime = "id"
argument = ""
buildOptions = ""

[benchmark.results.input]
cwd = ""
data = ""
file = ""
tags = ""
[benchmark.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = "20000 1"
runtime = "RootPPL"
argument = "Alcedinidae_crbd.cu"
buildOptions = ""
[[benchmark]]

[[benchmark.results]]
ms_run = [ 89.31689453125, 100.39306640625, 93.14794921875, 83.275146484375, 89.906982421875, 89.32177734375, 112.90185546875, 96.600830078125, 102.095703125, 105.416015625,]
ms_build = 498.184814453125
[[benchmark.results.post]]
stdout = [ "log normalization constant = -260.984216\n\n", "log normalization constant = -239.562114\n\n", "log normalization constant = -248.313045\n\n", "log normalization constant = -261.819647\n\n", "log normalization constant = -254.986445\n\n", "log normalization constant = -257.063015\n\n", "log normalization constant = -264.662419\n\n", "log normalization constant = -237.301851\n\n", "log normalization constant = -252.310202\n\n", "log normalization constant = -258.858914\n\n",]

[benchmark.results.post.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = ""
runtime = "id"
argument = ""
buildOptions = ""

[benchmark.results.input]
cwd = ""
data = ""
file = ""
tags = ""
[benchmark.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = "10000 1"
runtime = "RootPPL"
argument = "Alcedinidae_crbd.cu"
buildOptions = "--omp -j 32"
[[benchmark]]

[[benchmark.results]]
ms_run = [ 221.539794921875, 200.526123046875, 206.106201171875, 209.46728515625, 207.6611328125, 207.30029296875, 207.230224609375, 196.07177734375, 213.174072265625, 196.114990234375,]
ms_build = 4997.516845703125
[[benchmark.results.post]]
stdout = [ "log normalization constant = -262.507189\n\n", "log normalization constant = -263.674024\n\n", "log normalization constant = -249.067051\n\n", "log normalization constant = -242.218188\n\n", "log normalization constant = -256.337766\n\n", "log normalization constant = -259.862127\n\n", "log normalization constant = -248.029509\n\n", "log normalization constant = -254.253586\n\n", "log normalization constant = -260.638660\n\n", "log normalization constant = -264.014664\n\n",]

[benchmark.results.post.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = ""
runtime = "id"
argument = ""
buildOptions = ""

[benchmark.results.input]
cwd = ""
data = ""
file = ""
tags = ""
[benchmark.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = "10000 1"
runtime = "RootPPL"
argument = "Alcedinidae_crbd.cu"
buildOptions = "--arch 75 -j 32"
[[benchmark]]

[[benchmark.results]]
ms_run = [ 173.799072265625, 170.818115234375, 176.677001953125, 192.341064453125, 190.35205078125, 192.52392578125, 193.465087890625, 188.011962890625, 195.72412109375, 181.98583984375,]
ms_build = 2502.107177734375
[[benchmark.results.post]]
stdout = [ "log normalization constant = -257.371752\n\n", "log normalization constant = -257.371752\n\n", "log normalization constant = -257.371752\n\n", "log normalization constant = -267.126445\n\n", "log normalization constant = -267.126445\n\n", "log normalization constant = -267.126445\n\n", "log normalization constant = -267.126445\n\n", "log normalization constant = -267.126445\n\n", "log normalization constant = -267.126445\n\n", "log normalization constant = -261.687378\n\n",]

[benchmark.results.post.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = ""
runtime = "id"
argument = ""
buildOptions = ""

[benchmark.results.input]
cwd = ""
data = ""
file = ""
tags = ""
[benchmark.app]
cwd = "/home/viktor/ownCloud/miking-benchmarks/benchmark-suite/benchmarks/ppl/rootppl"
options = "10000 1"
runtime = "RootPPL"
argument = "Alcedinidae_crbd.cu"
buildOptions = ""


