timing="complete"

[[app]]
runtime = "CorePPL"
argument = "crbd.mc"
buildOptions = "--stack_size 100000"
options = "10000"
buildExtra = "node ../tree-utils/midppl-tree-parser.js ../input-data/Alcedinidae.phyjson 0.5 > tree-instance.mc"
cleanExtra = "rm -f tree-instance.mc"

[[post]]
runtime = "id"
