provides = "CorePPL2RootPPL"

[[command]]
required_executables = ["cppl", "rppl", "mi"]
build_command = "{buildExtra}; cppl -t rootppl {argument}; rppl out.cu -w {buildOptions}"
command = "./a.out {options}"
clean_command = "{cleanExtra}; rm -rf out.cu a.out build/"
