provides = "CorePPL2RootPPL"

[[command]]
required_executables = ["cppl", "rppl"]
build_command = "{buildExtra}; cppl {argument} -m rootppl-smc; rppl out.cu -w {buildOptions}"
command = "./a.out {options}"
clean_command = "{cleanExtra}; rm -rf out.cu a.out build/"
