provides = "CorePPL"

[[command]]
required_executables = ["midppl", "rootppl"]
build_command = "{buildExtra}; midppl {argument} -m rootppl-smc; rootppl out.cu {buildOptions}"
command = "./program {options}"
clean_command = "{cleanExtra}; rootppl clean; rm -rf ess.txt log_norm_const.txt out.cu program"
