provides = "phywppl"
[[command]]
required_executables = ["npm","webppl","node"]
build_command = "npm install; npm run wppl {buildOptions}"
command = "node --stack-size=1200 --max-old-space-size=4096 {argument}"
clean_command = "rm -rf node_modules; npm run clean"
