provides = "RootPPL"

[[command]]
required_executables = ["rootppl"]
build_command = "rootppl clean; rootppl {argument} {buildOptions}"
command = "./program {options}"
clean_command = "rootppl clean; rm -rf ess.txt log_norm_const.txt out.cu program"