provides = "RootPPL"

[[command]]
required_executables = ["rootppl"]
build_command = "rootppl clean; rootppl {argument}"
command = "./program {options}"
clean_command = "rm program; rm log_norm_const.txt; rm ess.txt"