timing="complete"

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mcmc-lightweight --align crbd-unaligned.mc"
options = "30000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mcmc-lightweight --align crbd-unaligned.mc"
options = "300000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mcmc-lightweight --align crbd-unaligned.mc"
options = "3000000"

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mcmc-lightweight crbd-unaligned.mc"
options = "30000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mcmc-lightweight crbd-unaligned.mc"
options = "300000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mcmc-lightweight crbd-unaligned.mc"
options = "3000000"

[[post]]
runtime = "Python3"
argument = "post.py"
options = ""
