timing="complete"

[[app]]
runtime = "CorePPL2RootPPL"
argument = "crbd-unaligned-fixed.mc --no-print-samples --resample align"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 2000"
options = "10000"

[[app]]
runtime = "CorePPL2RootPPL"
argument = "crbd-unaligned-fixed.mc --no-print-samples --resample align"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 2000"
options = "100000"

[[app]]
runtime = "CorePPL2RootPPL"
argument = "crbd-unaligned-fixed.mc --no-print-samples --resample align"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 2000"
options = "1000000"

[[app]]
runtime = "CorePPL2RootPPL"
argument = "crbd-unaligned-fixed.mc --no-print-samples --resample likelihood"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 2000"
options = "10000"

[[app]]
runtime = "CorePPL2RootPPL"
argument = "crbd-unaligned-fixed.mc --no-print-samples --resample likelihood"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 2000"
options = "100000"

[[app]]
runtime = "CorePPL2RootPPL"
argument = "crbd-unaligned-fixed.mc --no-print-samples --resample likelihood"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 2000"
options = "1000000"

[[post]]
runtime = "id"
