timing="complete"

[[app]]
runtime = "CorePPL"
argument = "hmm-aligned.mc --no-print-samples --resample manual"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 1000"
options = "10000"

[[app]]
runtime = "CorePPL"
argument = "hmm-aligned.mc --no-print-samples --resample manual"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 1000"
options = "100000"

[[app]]
runtime = "CorePPL"
argument = "hmm-aligned.mc --no-print-samples --resample manual"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 1000"
options = "1000000"

[[app]]
runtime = "CorePPL"
argument = "hmm-unaligned.mc --no-print-samples --resample manual"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 1000"
options = "10000"

[[app]]
runtime = "CorePPL"
argument = "hmm-unaligned.mc --no-print-samples --resample manual"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 1000"
options = "100000"

[[app]]
runtime = "CorePPL"
argument = "hmm-unaligned.mc --no-print-samples --resample manual"
buildOptions = "-j 32 --ess-threshold 1.0 --stack-size 1000"
options = "1000000"

[[post]]
runtime = "id"
