timing = "complete"

[[app]]
runtime = "RootPPL"
argument = "Lari_clads2_delayed.cu"
options = "8192 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "Lari_clads2_delayed.cu"
options = "16384 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "Lari_clads2_delayed.cu"
options = "32768 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "Lari_clads2_delayed.cu"
options =  "65536 1"
buildOptions = ""

[[post]]
runtime = "id"
