timing="complete"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "8192 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "8192 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "8192 1"
buildOptions = "--omp -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "16384 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "16384 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "16384 1"
buildOptions = "--omp -j 32"




[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "32768 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "32768 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "32768 1"
buildOptions = "--omp -j 32"


[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "65536 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options =  "65536 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "65536 1"
buildOptions = "--omp -j 32"


[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "131072 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options =  "131072 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "131072 1"
buildOptions = "--omp -j 32"


[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "262144 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options =  "262144 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "262144 1"
buildOptions = "--omp -j 32"


[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "524288 1"
buildOptions = ""

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options =  "524288 1"
buildOptions = "--arch 75 -j 32"

[[app]]
runtime = "RootPPL"
argument = "TitTyranRest_crbd_delayed.cu"
options = "524288 1"
buildOptions = "--omp -j 32"







[[post]]
runtime = "id"
