timing="complete"

[[app]]
runtime = "Birch"
argument = "infer"
options = "--config experiment1 --tree alcedinidae --nparticles 8192"


[[app]]
runtime = "Birch"
argument = "infer"
options = "--config experiment1 --tree alcedinidae --nparticles 16384"


[[app]]
runtime = "Birch"
argument = "infer"
options = "--config experiment1 --tree alcedinidae --nparticles 32768"


[[post]]
runtime = "Python3"
argument = "logz.py"
